###
GET http://localhost:7071/api/GetAllStreams

###
GET http://localhost:7071/api/GetStream?streamName=Test

###
GET http://localhost:7071/api/GetEvents?streamName=Test&startAtVersion=0

###
GET http://localhost:7071/api/GetSnapshots?streamName=Test

###
DELETE  http://localhost:7071/api/DeleteSnapshots?streamName=Test

###
POST http://localhost:7071/api/CreateSnapshot
Content-Type: application/json

{
    "data": "adsasda",
    "description": "This is a test",
    "streamName": "Test"
}

###
POST http://localhost:7071/api/AppendEvents
Content-Type: application/json

{
    "streamName": "Test1",
    "expectedVersion": 0,
    "events": [{
        "type": "Test", "data": "blahblah"
    }]
}