CREATE TABLE [Streams]
(
    [StreamId] [NVARCHAR](50) NOT NULL PRIMARY KEY,
	[Name] [NVARCHAR](256) NOT NULL UNIQUE,
	[Version] [INT] NOT NULL CHECK ([Version] >= (0)),
	[CreatedAt] [DATETIMEOFFSET](7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
	[UpdatedAt] [DATETIMEOFFSET](7) NULL
);

CREATE TABLE [Snapshots]
(
    [SnapshotId] [NVARCHAR](50) NOT NULL PRIMARY KEY,
	[StreamId] [NVARCHAR](50) NOT NULL FOREIGN KEY REFERENCES [Streams]([StreamId]),
	[Description] [NVARCHAR](256) NOT NULL,
	[Data] [NVARCHAR](MAX) NOT NULL,
	[Version] [INT] NOT NULL CHECK ([Version] >= (0)),
	[CreatedAt] [DATETIMEOFFSET](7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
	UNIQUE ([StreamId], [Version])
);

CREATE TABLE [Events] 
(
    [EventId] [NVARCHAR](50) NOT NULL PRIMARY KEY,
	[StreamId] [NVARCHAR](50) NOT NULL FOREIGN KEY REFERENCES [Streams]([StreamId]),
	[Type] [NVARCHAR](256) NOT NULL,
	[Data] [NVARCHAR](MAX) NOT NULL,
	[Version] [INT] NOT NULL CHECK ([Version] >= (0)),
	[CreatedAt] [DATETIMEOFFSET](7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
	UNIQUE ([StreamId], [Version])
);

CREATE TYPE NewEvent AS TABLE
(
	[EventId] [NVARCHAR](50) NOT NULL,
	[StreamId] [NVARCHAR](50) NOT NULL,
	[Type] [NVARCHAR](256) NOT NULL,
	[Data] [NVARCHAR](MAX) NOT NULL,
	[Version] [INT] NOT NULL
);